name: Build
on:
  push:
    tags:
      - 'rel/*'

jobs:
  build:
    name: Build Go binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [ amd64, arm64 ]
        goos: [linux, windows, darwin]
    steps:
      - name: Checkout
        uses: actions/checkout/@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/discord-werewolf-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout/@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download amd64 binary
        uses: actions/download-artifact@v4
        with:
          name: linux-amd64
          path: bin

      - name: Download amr64 binary
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64
          path: bin

      - name: Set tag
        run: |
          tag="${GITHUB_REF_NAME//rel\//}"
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/codebutter/discord-werewolf:${{ env.TAG }}
            docker.io/codebutter/discord-werewolf:latest
          platforms: linux/amd64,linux/arm64
